### ISSUE TITLE
System.Net.Http 4.0.0. requires NuGet 3.0 build fails consistently

### ISSUE THREAD

**Issue by cdm** [bitrise-steplib/steps-nuget-restore#12]
Build fails with the following error:
...
Successfully installed 'Xamarin.Forms 2.3.0.107'.
The 'System.Net.Http 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.0'.

Please upgrade the NuGet used for package restore as soon as possible?

**Comment by birmacher** [comment]
Hi @cdm,

We are shipping the VMs with the preinstalled tools, but you can always update it during the build. However you can set the required NuGet version in your NuGet restore step under your workflow editor.

Let me know if you need any help with it!

Cheers,
Barnabas

**Comment by birmacher** [comment]
I'm closing the issue, but if you hit any problems during setup ping me on intercom ( bottom right corner on Bitrise.io ) and I'm happy to help!

**Comment by cdm** [comment]
Thanks Barnabas, found the workflow option to upgrade as suggested
