### ISSUE TITLE
Auto retry if nuget restore fails

### ISSUE THREAD

**Issue by tamifist** [bitrise-steplib/steps-nuget-restore#15]
Hi, 
Is there any chance we could make the builds auto retry if nuget restore fails? This happens very often...

**Comment by viktorbenei** [comment]
Absolutely!
Thanks for reporting @tamifist !

@godrei pls schedule this

**Comment by tamifist** [comment]
Thank you! I also found Build Cache feature that might be useful: https://bitrise-io.github.io/devcenter/caching/about-caching/. Is there any chance to provide sample in context of Xamarin.Forms app? Should I add Cache:Pull before nugets restore step and Cache:Push as the last step in the Workflow? Is there any additional configuration required for both steps or just add to workflow?

**Comment by godrei** [comment]
Hi @tamifist ,
sorry for my late response and thanks for the issue report!

The step got a retry feature in [v1.0.2](https://github.com/bitrise-steplib/steps-nuget-restore/releases/tag/1.0.2).

You can find a topic about Xamarin dependency caching on our [discuss page](https://discuss.bitrise.io/t/how-to-cache-xamarin-dependencies/246).

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
