### ISSUE TITLE
bitrsie cli local config build 

### ISSUE THREAD

**Issue by AbinayaSubba** [bitrise-steplib/steps-nuget-restore#29]
i am trying to locally build the bitrise.yml . its a xamarian.android project. The cli is installed in linux machine.
I get below error when restoring nuget . 
$ /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono "/tmp/__nuget__566002565/nuget.exe" "restore" "Sam.sln"
Restore failed: fork/exec /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono: no such file or directory
Attempt 1 failed, retrying...
$ /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono "/tmp/__nuget__566002565/nuget.exe" "restore" "Sam.sln"
NuGet restore failed: fork/exec /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono: no such file or directory

**Comment by bitce** [comment]
Hi @zioncrush!

Can you please include a build URL here?
