### ISSUE TITLE
Nuget restore failed with version set to latest

### ISSUE THREAD

**Issue by freesatnaresh** [bitrise-steplib/steps-nuget-restore#30]
Hello,
I am seeing the Nuget restore failed consistently with version set to latest.
+------------------------------------------------------------------------------+

| (4) nuget-restore@1.1                                                        |
+------------------------------------------------------------------------------+
| id: nuget-restore                                                            |
| version: 1.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-05-26T16:43:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[16:43:41]  * [OK] Step dependency (go) installed, available. 
Configs:
- XamarinSolution: <SolutioName>.sln
- NuGetVersion: latest
Downloading NuGet latest version...
Download URL: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
Restoring NuGet packages...
$ /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__nuget__771458667/nuget.exe" "restore" "<SolutionName>.sln"
Restore failed: fork/exec /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono: no such file or directory
Attempt 1 failed, retrying...
$ /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__nuget__771458667/nuget.exe" "restore" "<SolutionName>.sln"
NuGet restore failed: fork/exec /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono: no such file or directory
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | nuget-restore@1.1 (exit code: 1)                              | 4.17 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-nuget-restore/issues |
| Source: https://github.com/bitrise-steplib/steps-nuget-restore               |

**Comment by istx25** [comment]
Hi @freesatnaresh,

Thank you for reaching out.

Can you share a link to a build that reproduces this error? And can you enable support access?
