### ISSUE TITLE
Unable to restore packages for solution due to nuget version

### ISSUE THREAD

**Issue by modplug** [bitrise-steplib/steps-nuget-restore#4]
When I try to update nugets for my solution it fails with the following output:

'MvvmCross' already has a dependency defined for 'MvvmCross.Core'.
'MvvmCross.Binding' already has a dependency defined for 'MvvmCross.Core'.
'MvvmCross.Core' already has a dependency defined for 'MvvmCross.Platform'.
'MvvmCross.Plugin.Color' already has a dependency defined for 'MvvmCross.Platform'.
ERRO[10:56:04] Step (nuget-restore@0.9.0) failed, error: (exit status 1) 

Afaik this happens because MvvmCross needs nuget version >= 3 and the default nuget version is 2.8.5.
Running "/Library/Frameworks/Mono.framework/Versions/Current/bin/nuget update self" will update to the latest version of nuget (3.3). Is there a way the nuget restore build-step can default to the newest version?

**Comment by birmacher** [comment]
Hey @modplug!

We released a tutorial on how to use a custom NuGet version: http://devcenter.bitrise.io/docs/nuget-restore-with-custom-nuget-version

Can you please try this if it solves your problem? Later - after testing it a bit - we will include it inside the step.
Let me know how it goes!

**Comment by modplug** [comment]
Hey @birmacher.

Your suggested fix worked just fine :)
